{% set name = "azure-umqtt-c" %}
{% set version = "2020-12-09" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/Azure/azure-umqtt-c/archive/{{ version.replace('.', '-') }}.tar.gz
    fn: {{ name }}-{{ version }}.tar.gz
    sha256: ab2eed774018cf1f1e7f21a72e2aeba83bbb2de9157be5a018f1dfb0cca3189d

build:
  number: 0
  skip: true  # [not win64]
  run_exports:
    - {{ pin_subpackage(name, exact=True) }}

requirements:
  build:
    - vs2017_win-64          # [win64]
    - cmake
    - ninja
  host:
    - azure-c-shared-utility
  run:
    - azure-c-shared-utility

test:
  commands:
    - if not exist %PREFIX%\\Library\\bin\\umqtt.dll exit 1  # [win]

about:
  home: https://github.com/Azure/azure-umqtt-c
  license: MIT
  license_file: LICENSE
  summary: |
    azure-umqtt-c is a general purpose library build for MQTT protocol

extra:
  recipe-maintainers:
    - seanyen
